name: Keep Render Alive (heartbeat)

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:        # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Mysterium Status Proxy
        run: |
          echo "$(date -u) - Sending heartbeat..."
          curl --fail --silent --show-error --max-time 20 "https://mysterium-status-proxy.onrender.com/status/mysterium" >/dev/null
          echo "✅ Ping successful."
